### PR TITLE
Remove LESS stylesheets

### PR DESCRIPTION
**Pull request by runlevel5**
Remove 2 less stylesheets to avoid error:

```
cannot load such file -- less
  (in /Users/trungle/.rbenv/versions/1.9.3-p286/lib/ruby/gems/1.9.1/bundler/gems/bootstrap-timepicker-rails-e080e84b12f2/vendor/assets/stylesheets/bootstrap-timepicker.less)
```

### CODE REVIEW

**Comment by tispratik** [comment]
Thanks @joneslee85

**Comment by GeoffTidey** [comment]
Hi @tispratik, this is still an issue, unless using the latest master from github.  Does rubygems need updating?

**Comment by tispratik** [comment]
Oh ok, can you please send a PR?

~Pratik

**Comment by crmaxx** [comment]
@GeoffTidey, I think my pull request fix this issue.

**Comment by martinstannard** [comment]
I installed yesterday and ran across this issue.

**Comment by crmaxx** [comment]
Do you installed from git ?

**Comment by martinstannard** [comment]
Yep, I added 

```
 gem 'bootstrap-timepicker-rails'
```

to my gemfile.

I'm going to fork and remove them myself.

**Comment by crmaxx** [comment]
To install from git you need use keyword `:git` in Gemfile. :)
I'm not sure that the author upload updated version to rubygems.org.

**Comment by martinstannard** [comment]
ah, thanks, will give that a try.

**Pull request merged**
