### PR TITLE
Update JS and CSS assets to latest version of bootstrap-timepicker

### PR DESCRIPTION
**Pull request by runlevel5**
The current JS and CSS assets are outdated - this bump them to latest

### CODE REVIEW

**Comment by tispratik** [comment]
Thanks again @joneslee85

**Comment by tispratik** [comment]
It says the pull request cannot be merged automatically. Did you rebase before making this commit?

**Comment by runlevel5** [comment]
Yes, likely the case, please `cherry-pick`:

```
git remote add joneslee85 git@github.com:joneslee85/bootstrap-timepicker-rails.git
git fetch joneslee85
git cherry-pick eb48307bc6f58b8acc92b642e443534d98cd4f25
```

I always prefer cherry-pick over auto-pull because there is no extra Pull Request commit

**Comment by tispratik** [comment]
Thanks, but I am getting 65 conflicts in one file. Is it possible for you
to redo your commit on a rebased master?

~Pratik

**Comment by runlevel5** [comment]
will do now

**Pull request closed without merging**
